language: ruby

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y liblzo2-dev
rvm:
  - 2.1.2
  - 2.1.0
  - 1.9.3
#  - jruby-18mode # JRuby in 1.8 mode ## C Extensions NOT supported
#  - jruby-19mode # JRuby in 1.9 mode ## C Extensions NOT supported
  - rbx-2.1.1
  - 1.8.7

