language: ruby
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y liblzo2-dev
rvm:
- 2.1.2
- 2.1.0
- 1.9.3
- rbx-2.2.10
#- 1.8.7
deploy:
  provider: rubygems
  api_key:
    secure: tSheWrPzHGbi7cIjZsbcA+Si6plURP17qPzcmzrRr5XCTFe1d8cdOtGHqroG56761PmXTZBD0Xs1aeQXX9S3QgRByLxiu4u3ARevpPVJnKCm8QQHgeGa2Jpbe/D+Ar3bu7ihuiI8d8FZzHb9sNXlBtqb91hW/Wfg4IMtl7QQceU=
  gem: lzop-file
  on:
    tags: true
    repo: trinitronx/lzop-file
